// constants.js

// --------------------
// Bakugan & Attributes
// --------------------

export const BAKUGAN = [
    { id: 0x00, name: "Dragonoid" },
    { id: 0x01, name: "Delta Dragonoid" },
    { id: 0x04, name: "Tigrerra" },
    { id: 0x05, name: "Blade Tigrerra" },
    { id: 0x06, name: "Preyas" },
    { id: 0x07, name: "Angelo" },
    { id: 0x08, name: "Diablo" },
    { id: 0x09, name: "Gorem" },
    { id: 0x0A, name: "Hammer Gorem" },
    { id: 0x0B, name: "Skyress" },
    { id: 0x0C, name: "Storm Skyress" },
    { id: 0x0D, name: "Hydranoid" },
    { id: 0x0E, name: "Dual Hydranoid" },
    { id: 0x19, name: "Reaper" },
    { id: 0x1A, name: "Cycloid" },
    { id: 0x1B, name: "Sirenoid" },
    { id: 0x1C, name: "Fourtress" },
    { id: 0x1D, name: "Tentaclear" },
    { id: 0x1E, name: "Harpus" },
    { id: 0x27, name: "Juggernoid" },
    { id: 0x28, name: "Robotallion" },
    { id: 0x29, name: "Saurus" },
    { id: 0x2A, name: "Serpenoid" },
    { id: 0x2B, name: "Falconeer" },
    { id: 0x2C, name: "Stinglash" },
    { id: 0x2D, name: "Griffon" },
    { id: 0x2E, name: "Laserman" },
    { id: 0x2F, name: "Centipoid" },
    { id: 0x30, name: "Fear Ripper" },
    { id: 0x31, name: "Siege" },
    { id: 0x32, name: "Terrorclaw" },
    { id: 0x34, name: "Gargonoid" },
    { id: 0x38, name: "Manion" },
    { id: 0x3A, name: "Ravenoid" },
    { id: 0x3C, name: "Warius" },
    { id: 0x3D, name: "Monarus" },
    { id: 0x3E, name: "Leonidas" },
    { id: 0x3F, name: "Omega Leonidas" },
    { id: 0x40, name: "Vladitor" },
    { id: 0x41, name: "Battle Ax Vladitor" },
];

export const ATTRIBUTES = [
    { id: 0x00, name: "Pyrus" },
    { id: 0x01, name: "Aquos" },
    { id: 0x02, name: "Subterra" },
    { id: 0x03, name: "Haos" },
    { id: 0x04, name: "Darkus" },
    { id: 0x05, name: "Ventus" },
];

// -------------
// Cards by type
// -------------

export const CARDS = {
    Gold: [
        { name: "Gargonoid", id: 0x27F8 },
        { name: "Manion", id: 0x27F9 },
        { name: "Terrorclaw", id: 0x27FA },
        { name: "Cycloid", id: 0x27FB },
        { name: "Gorem", id: 0x27FC },
        { name: "Ravenoid", id: 0x27FD },
        { name: "Warius", id: 0x27FE },
        { name: "Monarus", id: 0x27FF },
        { name: "Harpus", id: 0x2800 },
        { name: "Fourtress", id: 0x2801 },
        { name: "Sirenoid", id: 0x2802 },
        { name: "Dragonoid", id: 0x2803 },
        { name: "Delta Dragonoid", id: 0x2804 },
        { name: "Tigrerra", id: 0x2805 },
        { name: "Blade Tigrerra", id: 0x2806 },
        { name: "Preyas", id: 0x2807 },
        { name: "Preyas's", id: 0x2808 },
        { name: "Hammer Gorem", id: 0x2809 },
        { name: "Skyress", id: 0x280A },
        { name: "Storm Skyress", id: 0x280B },
        { name: "Hydranoid", id: 0x280C },
        { name: "Dual Hydranoid", id: 0x280D },
        { name: "Reaper", id: 0x280E },
        { name: "Tentaclear", id: 0x280F },
        { name: "Juggernoid", id: 0x2810 },
        { name: "Robotallion", id: 0x2811 },
        { name: "Saurus", id: 0x2812 },
        { name: "Serpenoid", id: 0x2813 },
        { name: "Falconeer", id: 0x2814 },
        { name: "Stinglash", id: 0x2815 },
        { name: "Griffon", id: 0x2816 },
        { name: "Laserman", id: 0x2817 },
        { name: "Centipod", id: 0x2818 },
        { name: "Fear Ripper", id: 0x2819 },
        { name: "Siege", id: 0x281A },
        { name: "Leonidas", id: 0x28A2 },
        { name: "Omega Leonidas", id: 0x28A3 },
        { name: "Vladitor", id: 0x28A4 },
        { name: "Battle Ax Vladitor", id: 0x28A5 },
    ],

    Silver: [
        { name: "Fire Pit", id: 0x281B },
        { name: "Muddy Ground", id: 0x281C },
        { name: "Light Burst", id: 0x281D },
        { name: "Tsunami", id: 0x281E },
        { name: "Dusk", id: 0x281F },
        { name: "High Energy", id: 0x2820 },
        { name: "Tornado Alley", id: 0x2821 },
        { name: "Whirlpool", id: 0x2822 },
        { name: "Earthen Mound", id: 0x2823 },
        { name: "Elevated Field", id: 0x2824 },
        { name: "Force Wind", id: 0x2825 },
        { name: "Low Energy", id: 0x2826 },
        { name: "Sandstorm", id: 0x2827 },
        { name: "Haunted Night", id: 0x2828 },
        { name: "Sunrise", id: 0x2829 },
        { name: "Volcanic Lake", id: 0x282A },
        { name: "Aquos Vortex", id: 0x282B },
        { name: "Powder Keg", id: 0x282C },
        { name: "Heavy Surf", id: 0x282D },
        { name: "The Cliffs", id: 0x282E },
        { name: "Vacuum", id: 0x282F },
        { name: "Pit Dweller", id: 0x2830 },
        { name: "Nightmare", id: 0x2831 },
        { name: "The Spires", id: 0x2832 },
        { name: "Spitting Fire", id: 0x2833 },
        { name: "Earthen Wave", id: 0x2834 },
        { name: "Sun Spot", id: 0x2835 },
        { name: "Black Hole", id: 0x2836 },
        { name: "Wind Farm", id: 0x2837 },
        { name: "Whirlpool Preyas", id: 0x2838 },
        { name: "Fields of Lava", id: 0x2839 },
        { name: "Blue Sky", id: 0x283A },
    ],

    Bronze: [
        { name: "Rising Blow", id: 0x283B },
        { name: "Lava Fields", id: 0x283C },
        { name: "Earth Wind and Fire", id: 0x283D },
        { name: "Energy From All", id: 0x283E },
        { name: "Rainbow", id: 0x283F },
        { name: "Mega Warrior", id: 0x2840 },
        { name: "G Power Exchange", id: 0x2841 },
        { name: "G Power Swap", id: 0x2842 },
        { name: "Catch Up", id: 0x2843 },
        { name: "Ability Block", id: 0x2844 },
        { name: "Leap of Strength", id: 0x2845 },
        { name: "Stand Your Ground", id: 0x2846 },
        { name: "High Price", id: 0x2847 },
        { name: "Quick Charge", id: 0x2848 },
        { name: "Lock and Load", id: 0x2849 },
        { name: "Quick Strike", id: 0x284A },
        { name: "Ground Strike", id: 0x284B },
        { name: "Heated Exchange", id: 0x284C },
        { name: "Wind Gust Attack", id: 0x284D },
        { name: "Lift", id: 0x284E },
        { name: "Bait", id: 0x284F },
        { name: "Power Drain", id: 0x2850 },
        { name: "Fire Breath", id: 0x2851 },
        { name: "Stinger", id: 0x2852 },
        { name: "Delayed Attack", id: 0x2853 },
        { name: "Change of Fate", id: 0x2854 },
        { name: "Overpower", id: 0x2855 },
        { name: "Lightning Gate", id: 0x2856 },
        { name: "Sinkhole", id: 0x2857 },
        { name: "Tricky Gate", id: 0x2858 },
        { name: "Bakugan Duo", id: 0x2859 },
    ],

    Red: [
        { name: "Stuck", id: 0x285A },
        { name: "A Hand Up", id: 0x285B },
        { name: "Masquerade's Throw", id: 0x285C },
        { name: "Dan's Throw", id: 0x285D },
        { name: "Unexpected Guest", id: 0x285E },
        { name: "Julie's Throw", id: 0x285F },
        { name: "Clean Slate", id: 0x2860 },
        { name: "Marionette", id: 0x2861 },
        { name: "Perfect Aim", id: 0x2862 },
        { name: "Runo's Throw", id: 0x2863 },
        { name: "Marucho's Throw", id: 0x2864 },
        { name: "Uneven Bump", id: 0x2865 },
        { name: "Battle Gate", id: 0x2866 },
        { name: "Shun's Throw", id: 0x2867 },
        { name: "Dark Void", id: 0x2868 },
        { name: "Fire Wall", id: 0x28AD },
        { name: "Dive Mirage", id: 0x28AE },
        { name: "Blow Away", id: 0x28AF },
        { name: "Grand Slide", id: 0x28B0 },
        { name: "Spark Out", id: 0x28B1 },
        { name: "Dimension 4", id: 0x28B2 },
        { name: "Shinning Nova", id: 0x28B3 },
        { name: "Quick Draw", id: 0x28B4 },
        { name: "Power Surge", id: 0x28B5 },
        { name: "Timing Battle", id: 0x28B6 },
    ],

    Green: [
        { name: "Leap Ahead", id: 0x2869 },
        { name: "Blowing Winds", id: 0x286A },
        { name: "Ground Attack", id: 0x286B },
        { name: "Tigrerra's Energy", id: 0x286C },
        { name: "Triple Threat", id: 0x286D },
        { name: "Equalizer", id: 0x286E },
        { name: "Ground Shutdown", id: 0x286F },
        { name: "Mega Impact", id: 0x2870 },
        { name: "Chaos of the Darkness", id: 0x2871 },
        { name: "Darkus Gazer", id: 0x2872 },
        { name: "Boosted Dragon", id: 0x2873 },
        { name: "Meteor Strike Dragon", id: 0x2874 },
        { name: "Destruction Meteor Storm", id: 0x2875 },
        { name: "Flare Binder", id: 0x2876 },
        { name: "Cut in Saber", id: 0x2877 },
        { name: "Velocity Fang", id: 0x2878 },
        { name: "Blue Stealth", id: 0x2879 },
        { name: "Grand Impact", id: 0x287A },
        { name: "Fire Storm", id: 0x287B },
        { name: "Right Giganto", id: 0x287C },
        { name: "Forcing Wave", id: 0x287D },
        { name: "Face of Rage", id: 0x287E },
        { name: "Feather Storm", id: 0x287F },
        { name: "With Darkness", id: 0x2880 },
        { name: "Alpha Blaster", id: 0x28A6 },
        { name: "Omega Erasor", id: 0x28A7 },
        { name: "Dark Sphere Impact", id: 0x28A8 },
        { name: "Thousand Destroyer", id: 0x28A9 },
    ],

    Blue: [
        { name: "Bright Light", id: 0x2881 },
        { name: "G Power Boost", id: 0x2882 },
        { name: "G Power Dump", id: 0x2883 },
        { name: "Blaze", id: 0x2884 },
        { name: "Home Advantage", id: 0x2885 },
        { name: "Power From Darkness", id: 0x2886 },
        { name: "Summon Wave", id: 0x2887 },
        { name: "Mega Impact", id: 0x2888 },
        { name: "Hot Wind", id: 0x2889 },
        { name: "Flash", id: 0x288A },
        { name: "G Power Bonus", id: 0x288B },
        { name: "G Power Up", id: 0x288C },
        { name: "Dark Growth", id: 0x288D },
        { name: "Circle of Fire", id: 0x288E },
        { name: "Updraft", id: 0x288F },
        { name: "Fire Menace", id: 0x2890 },
        { name: "Intense Roar", id: 0x2891 },
        { name: "Triangle of Power", id: 0x2892 },
        { name: "Power Triangle", id: 0x2893 },
        { name: "Heated Glow", id: 0x2894 },
        { name: "Dark Circumference", id: 0x2895 },
        { name: "Gusty Maneuver", id: 0x2896 },
        { name: "Pyrus and Darkus Combo", id: 0x2897 },
        { name: "Ventus and Haos Combo", id: 0x2898 },
        { name: "Subterra and Aquos Combo", id: 0x2899 },
        { name: "Pyrus and Subterra Combo", id: 0x289A },
        { name: "Subterra and Haos Combo", id: 0x289B },
        { name: "Haos and Darkus Combo", id: 0x289C },
        { name: "Darkus and Aquos Combo", id: 0x289D },
        { name: "Aquos and Ventus Combo", id: 0x289E },
        { name: "Ventus and Pyrus Combo", id: 0x289F },
        { name: "Pyrus Aquos and Haos Combo", id: 0x28A0 },
        { name: "Subterra Ventus and Darkus Combo", id: 0x28A1 },
        { name: "Bakugan Spin", id: 0x28AA },
        { name: "G Power Spin", id: 0x28AB },
        { name: "Turn of Fortune", id: 0x28AC },
    ],
};

// -------------
// Styling data
// -------------

export const STYLING = {
    Skin: {
        Tone: [
            { name: "White", id: 0x00 },
            { name: "Tan", id: 0x01 },
            { name: "Brown", id: 0x02 },
            { name: "Black", id: 0x03 },
            { name: "Olive", id: 0x04 },
        ],
    },
    Hair: {
        Style: [
            { name: "Spiky", id: 0x00 },
            { name: "Short", id: 0x01 },
            { name: "Styled", id: 0x02 },
            { name: "Untidy", id: 0x03 },
            { name: "Mohawk", id: 0x04 },
            { name: "Fro", id: 0x05 },
            { name: "Close Buzz", id: 0x06 },
            { name: "Cornrows", id: 0x07 },
        ],
        Colour: [
            { name: "Brown", id: 0x00 },
            { name: "Black", id: 0x01 },
            { name: "Blonde", id: 0x02 },
            { name: "Red", id: 0x03 },
            { name: "Grey", id: 0x04 },
            { name: "Light Brown", id: 0x05 },
        ],
    },
    Eyes: {
        Shape: [
            { name: "Small", id: 0x00 },
            { name: "Angled Up", id: 0x01 },
            { name: "Angled Down", id: 0x02 },
            { name: "Large", id: 0x03 },
        ],
        Colour: [
            { name: "Red", id: 0x00 },
            { name: "Brown", id: 0x01 },
            { name: "Blue", id: 0x02 },
            { name: "Green", id: 0x03 },
            { name: "Purple", id: 0x04 },
            { name: "Black", id: 0x05 },
        ],
    },
    Mouth: {
        Shape: [
            { name: "Thin", id: 0x00 },
            { name: "Full", id: 0x01 },
        ],
    },
    Nose: {
        Shape: [
            { name: "Small", id: 0x00 },
            { name: "Snub", id: 0x01 },
            { name: "Long", id: 0x02 },
            { name: "Bridge", id: 0x03 },
            { name: "Button", id: 0x04 },
        ],
    },
    Glasses: {
        Style: [
            { name: "None", id: 0x00 },
            { name: "Square", id: 0x01 },
            { name: "Oval", id: 0x02 },
            { name: "Sporty", id: 0x03 },
            { name: "Aviators", id: 0x04 },
        ],
        Colour: [
            { name: "Red", id: 0x00 },
            { name: "Black", id: 0x01 },
            { name: "Blue", id: 0x02 },
            { name: "White", id: 0x03 },
        ],
        Lens: [
            { name: "Clear", id: 0x00 },
            { name: "Black", id: 0x01 },
            { name: "Brown", id: 0x02 },
            { name: "Orange", id: 0x03 },
            { name: "Grey", id: 0x04 },
        ],
    },
    Hat: {
        Style: [
            { name: "None", id: 0x00 },
            { name: "Baseball", id: 0x01 },
            { name: "Knit", id: 0x02 },
            { name: "Wide Brim", id: 0x03 },
            { name: "Cabby", id: 0x04 },
            { name: "Cowboy", id: 0x05 },
        ],
        Colour: [
            { name: "Black", id: 0x00 },
            { name: "Blue", id: 0x01 },
            { name: "Grey", id: 0x02 },
            { name: "Red", id: 0x03 },
            { name: "Yellow", id: 0x04 },
            { name: "White", id: 0x05 },
        ],
    },
    Shirt: {
        Style: [
            { name: "Stylish", id: 0x00 },
            { name: "Jacket", id: 0x01 },
            { name: "T-Shirt", id: 0x02 },
            { name: "Tank Top", id: 0x03 },
            { name: "Leather Jacket", id: 0x04 },
            { name: "Japanese", id: 0x05 },
        ],
        Colour: [
            { name: "Red", id: 0x00 },
            { name: "Black", id: 0x01 },
            { name: "Blue", id: 0x02 },
            { name: "Yellow", id: 0x03 },
            { name: "White", id: 0x04 },
            { name: "Brown", id: 0x05 },
        ],
        Accent: [
            { name: "Pyrus", id: 0x00 },
            { name: "Aquos", id: 0x01 },
            { name: "Subterra", id: 0x02 },
            { name: "Haos", id: 0x03 },
            { name: "Darkus", id: 0x04 },
            { name: "Ventus", id: 0x05 },
        ],
    },
    Pants: {
        Style: [
            { name: "Athletic", id: 0x00 },
            { name: "Shorts", id: 0x01 },
            { name: "Jeans", id: 0x02 },
            { name: "Long", id: 0x03 },
            { name: "Chaps", id: 0x04 },
            { name: "Japanese", id: 0x05 },
        ],
        Colour: [
            { name: "Red", id: 0x00 },
            { name: "Black", id: 0x01 },
            { name: "Blue", id: 0x02 },
            { name: "Yellow", id: 0x03 },
            { name: "White", id: 0x04 },
            { name: "Brown", id: 0x05 },
        ],
        Accent: [
            { name: "Pyrus", id: 0x00 },
            { name: "Aquos", id: 0x01 },
            { name: "Subterra", id: 0x02 },
            { name: "Haos", id: 0x03 },
            { name: "Darkus", id: 0x04 },
            { name: "Ventus", id: 0x05 },
        ],
    },
    Shoes: {
        Style: [
            { name: "Sneakers", id: 0x00 },
            { name: "Hiking", id: 0x01 },
            { name: "Athletic", id: 0x02 },
            { name: "Leather Boots", id: 0x03 },
            { name: "Army Boots", id: 0x04 },
            { name: "Japanese", id: 0x05 },
        ],
        Colour: [
            { name: "Red", id: 0x00 },
            { name: "Black", id: 0x01 },
            { name: "Blue", id: 0x02 },
            { name: "Yellow", id: 0x03 },
            { name: "White", id: 0x04 },
            { name: "Brown", id: 0x05 },
        ],
    },
    Gloves: {
        Style: [
            { name: "None", id: 0x00 },
            { name: "Normal", id: 0x01 },
            { name: "Dan's Gloves", id: 0x02 },
            { name: "Shun's Gloves", id: 0x03 },
            { name: "White", id: 0x04 },
            { name: "Fingerless", id: 0x05 },
        ],
    },
    Watch: {
        Color: [
            { name: "Pyrus", id: 0x00 },
            { name: "Aquos", id: 0x01 },
            { name: "Subterra", id: 0x02 },
            { name: "Haos", id: 0x03 },
            { name: "Darkus", id: 0x04 },
            { name: "Ventus", id: 0x05 },
        ],
    },
};

// ------------------------
// Styling field definition
// ------------------------

export const STYLING_FIELDS = [
    { key: "skinTone", label: "Skin tone", byteOffset: 0, group: "Skin", prop: "Tone" },

    { key: "hairStyle", label: "Hair style", byteOffset: 2, group: "Hair", prop: "Style" },
    { key: "hairColour", label: "Hair colour", byteOffset: 4, group: "Hair", prop: "Colour" },

    { key: "eyeShape", label: "Eye shape", byteOffset: 6, group: "Eyes", prop: "Shape" },
    { key: "eyeColour", label: "Eye colour", byteOffset: 8, group: "Eyes", prop: "Colour" },

    { key: "mouthShape", label: "Mouth shape", byteOffset: 10, group: "Mouth", prop: "Shape" },

    { key: "noseShape", label: "Nose shape", byteOffset: 12, group: "Nose", prop: "Shape" },

    { key: "glassesStyle", label: "Glasses style", byteOffset: 14, group: "Glasses", prop: "Style" },
    { key: "glassesColour", label: "Glasses colour", byteOffset: 16, group: "Glasses", prop: "Colour" },
    { key: "lensColour", label: "Lens colour", byteOffset: 18, group: "Glasses", prop: "Lens" },

    { key: "hatStyle", label: "Hat style", byteOffset: 20, group: "Hat", prop: "Style" },
    { key: "hatColour", label: "Hat colour", byteOffset: 22, group: "Hat", prop: "Colour" },

    { key: "shirtStyle", label: "Shirt style", byteOffset: 24, group: "Shirt", prop: "Style" },
    { key: "shirtColour", label: "Shirt colour", byteOffset: 26, group: "Shirt", prop: "Colour" },
    { key: "shirtAccent", label: "Shirt accent", byteOffset: 28, group: "Shirt", prop: "Accent" },

    { key: "pantsStyle", label: "Pants style", byteOffset: 30, group: "Pants", prop: "Style" },
    { key: "pantsColour", label: "Pants colour", byteOffset: 32, group: "Pants", prop: "Colour" },
    { key: "pantsAccent", label: "Pants accent", byteOffset: 34, group: "Pants", prop: "Accent" },

    { key: "shoesStyle", label: "Shoes style", byteOffset: 36, group: "Shoes", prop: "Style" },
    { key: "shoeColour", label: "Shoe colour", byteOffset: 38, group: "Shoes", prop: "Colour" },
    
    { key: "glovesStyle", label: "Gloves", byteOffset: 40, group: "Gloves", prop: "Style" },

    { key: "watchColour", label: "Watch colour", byteOffset: 44, group: "Watch", prop: "Color" },
];

export function getStylingOptions(fieldKey) {
    const field = STYLING_FIELDS.find((f) => f.key === fieldKey);
    if (!field) return [];
    const groupObj = STYLING[field.group];
    if (!groupObj) return [];
    const options = groupObj[field.prop];
    return options || [];
}
